apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-fxzj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vlgi-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-fxzj@sha256:20fef798aeaff23b3cafc5e09fc35d012a48851a76ec7164c26cf93014b8ec1e
        name: my-python
        resources: {}
status: {}
